// receive_logs.go — the CONSUMER.
// Every copy of this program you run creates its OWN private queue and
// binds it to the "logs" exchange. Because the exchange is "fanout",
// every running receiver gets a copy of every message — that's the
// broadcast / pub-sub behavior.
package main

import (
	"context"
	"errors"
	"log"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

const brokerURI = "amqp://guest:guest@localhost:5672/"

func main() {
	ctx := context.Background()

	env := rmq.NewEnvironment(brokerURI, nil)
	conn, err := env.NewConnection(ctx)
	if err != nil {
		log.Panicf("Failed to connect to RabbitMQ: %v", err)
	}
	defer func() {
		_ = env.CloseConnections(context.Background())
	}()

	// Declare the same exchange the producer declares. Order doesn't
	// matter — whichever program starts first creates it, the other
	// just confirms it already exists (declaring is idempotent).
	_, err = conn.Management().DeclareExchange(ctx, &rmq.FanOutExchangeSpecification{Name: "logs"})
	if err != nil {
		log.Panicf("Failed to declare an exchange: %v", err)
	}

	// Declare a queue with NO name of our own — the broker will
	// auto-generate a random unique name for it.
	//   IsExclusive:  true  -> only this connection can use this queue;
	//                          it's not shared with other receivers.
	//   IsAutoDelete: true  -> the queue is deleted automatically as
	//                          soon as this program disconnects, so we
	//                          don't leave junk queues behind.
	// This is exactly what we want: each receiver gets its own
	// throwaway mailbox.
	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  true,
		IsAutoDelete: true,
	})
	if err != nil {
		log.Panicf("Failed to declare a queue: %v", err)
	}

	// Bind (connect) our private queue to the "logs" exchange, so the
	// exchange knows to copy messages into it. BindingKey is "" because
	// fanout exchanges ignore routing keys anyway.
	_, err = conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
		SourceExchange:   "logs",
		DestinationQueue: qInfo.Name(),
		BindingKey:       "",
	})
	if err != nil {
		log.Panicf("Failed to bind a queue: %v", err)
	}

	// Create a consumer attached to our queue — this is what actually
	// pulls messages off the queue for us.
	consumer, err := conn.NewConsumer(ctx, qInfo.Name(), nil)
	if err != nil {
		log.Panicf("Failed to create consumer: %v", err)
	}
	defer func() { _ = consumer.Close(context.Background()) }()

	log.Printf(" [*] Waiting for logs. To exit press CTRL+C")

	// Loop forever, blocking on Receive() until a message arrives (or
	// the program is cancelled, e.g. via Ctrl+C).
	for {
		delivery, err := consumer.Receive(ctx)
		if err != nil {
			// context.Canceled happens on a clean shutdown (Ctrl+C) —
			// treat that as a normal exit, not an error.
			if errors.Is(err, context.Canceled) {
				return
			}
			log.Panicf("Failed to receive a message: %v", err)
		}

		msg := delivery.Message()
		var body string
		if len(msg.Data) > 0 {
			body = string(msg.Data[0])
		}
		log.Printf(" [x] %s", body)

		// Tell the broker "I successfully processed this message, you
		// can remove it from the queue now." Without this acknowledgment,
		// AMQP would eventually consider the message undelivered.
		err = delivery.Accept(ctx)
		if err != nil {
			log.Panicf("Failed to accept message: %v", err)
		}
	}
}
