// receive_logs_direct.go — the CONSUMER for the "routing" tutorial.
//
// Like tutorial 3's receiver, this creates its own private, temporary
// queue. The difference: instead of one empty-key binding that catches
// everything, it creates ONE BINDING PER SEVERITY LEVEL the user asks
// for on the command line. Only messages published with a matching
// routing key land in this queue.
//
// Example:
//
//	go run . warning error
//
// binds to both "warning" and "error" — this receiver will get those,
// but NOT "info" messages.
package main

import (
	"context"
	"errors"
	"log"
	"os"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

const brokerURI = "amqp://guest:guest@localhost:5672/"

func main() {
	ctx := context.Background()

	env := rmq.NewEnvironment(brokerURI, nil)
	conn, err := env.NewConnection(ctx)
	if err != nil {
		log.Panicf("Failed to connect to RabbitMQ: %v", err)
	}
	defer func() {
		_ = env.CloseConnections(context.Background())
	}()

	// Same direct exchange the producer uses. Declaring it here too is
	// safe (and necessary in case this receiver starts before any
	// emitter has run).
	_, err = conn.Management().DeclareExchange(ctx, &rmq.DirectExchangeSpecification{Name: "logs_direct"})
	if err != nil {
		log.Panicf("Failed to declare an exchange: %v", err)
	}

	// Same private, throwaway queue pattern as tutorial 3: no name,
	// exclusive to this connection, deleted automatically on disconnect.
	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  true,
		IsAutoDelete: true,
	})
	if err != nil {
		log.Panicf("Failed to declare a queue: %v", err)
	}

	// The severities to listen for come from the command line, e.g.:
	//   go run . info warn
	severities := os.Args[1:]
	if len(severities) == 0 {
		log.Printf("Usage: %s [info] [warning] [error]", os.Args[0])
		os.Exit(0)
	}

	// Create one binding per requested severity. This is the key new
	// piece compared to tutorial 3, where a single binding with an
	// empty key caught every message. Here, only messages whose routing
	// key exactly matches one of these binding keys will be routed into
	// our queue.
	for _, severity := range severities {
		log.Printf("Binding queue to exchange logs_direct with routing key %s", severity)
		_, err = conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
			SourceExchange:   "logs_direct",
			DestinationQueue: qInfo.Name(),
			BindingKey:       severity,
		})
		if err != nil {
			log.Panicf("Failed to bind a queue: %v", err)
		}
	}

	consumer, err := conn.NewConsumer(ctx, qInfo.Name(), nil)
	if err != nil {
		log.Panicf("Failed to create consumer: %v", err)
	}
	defer func() { _ = consumer.Close(context.Background()) }()

	log.Printf(" [*] Waiting for logs. To exit press CTRL+C")
	for {
		delivery, err := consumer.Receive(ctx)
		if err != nil {
			if errors.Is(err, context.Canceled) {
				return
			}
			log.Panicf("Failed to receive a message: %v", err)
		}

		msg := delivery.Message()
		var body string
		if len(msg.Data) > 0 {
			body = string(msg.Data[0])
		}
		log.Printf(" [x] %s", body)

		err = delivery.Accept(ctx)
		if err != nil {
			log.Panicf("Failed to accept message: %v", err)
		}
	}
}
