// receive_logs_topic.go — the CONSUMER for the "topics" tutorial.
//
// Same private/exclusive/auto-delete queue pattern as tutorials 3 and 4.
// The difference is what gets passed as the binding key: instead of an
// exact severity like "warning", you can now pass PATTERNS containing
// wildcards:
//
//   - matches exactly ONE word
//     #   matches ZERO OR MORE words
//
// Examples:
//
//	go run . "kern.*"              -> all severities from facility "kern"
//	go run . "*.critical"          -> "critical" severity from any facility
//	go run . "kern.critical" "auth.warn"  -> two exact-match bindings at once
package main

import (
	"context"
	"errors"
	"log"
	"os"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

const brokerURI = "amqp://guest:guest@localhost:5672/"

func main() {
	ctx := context.Background()

	env := rmq.NewEnvironment(brokerURI, nil)
	conn, err := env.NewConnection(ctx)
	if err != nil {
		log.Panicf("Failed to connect to RabbitMQ: %v", err)
	}
	defer func() {
		_ = env.CloseConnections(context.Background())
	}()

	// Same topic exchange the producer publishes to.
	_, err = conn.Management().DeclareExchange(ctx, &rmq.TopicExchangeSpecification{Name: "logs_topic"})
	if err != nil {
		log.Panicf("Failed to declare an exchange: %v", err)
	}

	// Same private, throwaway queue pattern as tutorials 3 and 4.
	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  true,
		IsAutoDelete: true,
	})
	if err != nil {
		log.Panicf("Failed to declare a queue: %v", err)
	}

	// Each command-line argument is a binding PATTERN, not necessarily
	// an exact key. The exchange does the wildcard matching for us —
	// we just register the pattern as-is.
	patterns := os.Args[1:]
	if len(patterns) == 0 {
		log.Printf("Usage: %s [binding_key]...", os.Args[0])
		log.Printf(`e.g.: %s "kern.*" "*.critical"`, os.Args[0])
		os.Exit(0)
	}

	for _, pattern := range patterns {
		log.Printf("Binding queue to exchange logs_topic with pattern %s", pattern)
		_, err = conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
			SourceExchange:   "logs_topic",
			DestinationQueue: qInfo.Name(),
			BindingKey:       pattern,
		})
		if err != nil {
			log.Panicf("Failed to bind a queue: %v", err)
		}
	}

	consumer, err := conn.NewConsumer(ctx, qInfo.Name(), nil)
	if err != nil {
		log.Panicf("Failed to create consumer: %v", err)
	}
	defer func() { _ = consumer.Close(context.Background()) }()

	log.Printf(" [*] Waiting for logs. To exit press CTRL+C")
	for {
		delivery, err := consumer.Receive(ctx)
		if err != nil {
			if errors.Is(err, context.Canceled) {
				return
			}
			log.Panicf("Failed to receive a message: %v", err)
		}

		msg := delivery.Message()
		var body string
		if len(msg.Data) > 0 {
			body = string(msg.Data[0])
		}
		log.Printf(" [x] %s", body)

		err = delivery.Accept(ctx)
		if err != nil {
			log.Panicf("Failed to accept message: %v", err)
		}
	}
}
